---
sudo: false

language: go

go:
  - 1.6
  - 1.7.x

install:
  - go get github.com/onsi/ginkgo/ginkgo
  - "curl https://glide.sh/get | sh"
  - glide install

script:
  - go test $(go list ./... | grep -v /vendor/) -cover
